# Generated by Django 3.1.4 on 2021-09-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipping', models.CharField(choices=[('deliver_by_bike', 'deliver_by_bike'), ('deliver_by_van', 'deliver_by_van')], max_length=20)),
                ('status', models.CharField(choices=[('1', 'cancel'), ('2', 'success'), ('3', 'process'), ('4', 'deliver'), ('5', 'send'), ('6', 'active')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
