# Generated by Django 3.2.7 on 2021-09-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'expired')], default=1, max_length=20),
        ),
    ]
