# Generated by Django 3.2.7 on 2021-09-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_discountcode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'expired')], default=1),
        ),
    ]
