# Generated by Django 3.2.7 on 2021-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('success', 'success'), ('process', 'process'), ('deliver', 'deliver'), ('send', 'send'), ('active', 'active')], max_length=20),
        ),
    ]
