# Generated by Django 3.2.7 on 2021-10-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-product',), 'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
    ]
