# Generated by Django 3.2.7 on 2021-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('send', 'send'), ('deliver', 'deliver')], default='process', max_length=20, verbose_name='status'),
        ),
    ]
