# Generated by Django 3.2.7 on 2021-09-24 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0012_alter_address_postalcode'),
        ('orders', '0008_rename_item_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=50)),
                ('customer', models.ManyToManyField(related_name='coupon', to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=50)),
                ('product', models.ManyToManyField(related_name='discount', to='products.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
