# Generated by Django 3.2.7 on 2021-09-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210924_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
