# Generated by Django 3.2.7 on 2021-09-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
