# Generated by Django 3.2.7 on 2021-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
