# Generated by Django 3.2.7 on 2021-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.CharField(max_length=10),
        ),
    ]
